server:
  servlet:
    session:
      timeout: 1800
      #tracking-modes: cookie


spring:
  application:
    name: calendar
  profiles:
    active: dev

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  
mybatis:
  config-location: classpath:mapper/config/config.xml
  mapper-locations: classpath:mapper/sql/**/*.xml
  type-aliases-package: com.jjang051.calendar.dto

file:
  path: C:/upload/